### ISSUE TITLE
Docs shouldn't ask the user to _sudo_ npm install

### ISSUE THREAD

**Issue by shanehandley** [zlanguage/zlanguage.github.io#2]
> $ sudo npm install -g @zlanguage/zcomp

It does not appear to be necessary and can cause issues. It should be removed.

**Comment by N8python** [comment]
Oh, thx!

**Comment by shanehandley** [comment]
Ah sorry to re-open but there is still one reference for the yarn install >

> sudo yarn global add @zlanguage/zcomp globby
